apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:39:27Z"
  name: carts-canary
  resourceVersion: "932716"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 92ab9ac2-0c53-11ea-86c9-42010a840286
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
