---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:47:14Z"
  name: carts-canary
  resourceVersion: "934643"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: a9501cb3-0c54-11ea-86c9-42010a840286
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
